### PR TITLE
Fix winglets livery animation problem

### PR DESCRIPTION
**Pull request by vezza**
Fix winglets livery animation problem

### CODE REVIEW

**Comment by FGDATA** [comment]
@it0uchpods @YV3399

**Comment by YV3399** [comment]
Thanks @vezza

**Comment by vezza** [comment]
Well, I'm still working on that because the problem is still there, tomorrow I'll test and eventually create a nuw pull request... bye!

**Comment by Octal450** [comment]
Nice. tag me when you have it done please.

Kind Regards,
Josh

**Comment by vezza** [comment]
@it0uchpods ok, at the moment I've tested the changes I made and it seems it is working fine but I found another problem... the winglets position isn't correct, the left winglet is detached from the wing... hope to be able to fix that issue too before commit.

**Pull request merged**
